# Generated by Django 5.2.1 on 2025-06-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.IntegerField()),
                ('student_eval', models.FloatField()),
                ('workload', models.FloatField()),
                ('prep', models.FloatField()),
                ('deloading', models.BooleanField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyDataUpload',
        ),
    ]
