# Generated by Django 5.2.1 on 2025-06-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_facultyrecord_delete_facultydataupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('campus', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('2nd Sem 2023–2024', '2nd Sem 2023–2024'), ('1st Sem 2024–2025', '1st Sem 2024–2025')], max_length=25)),
                ('student_evaluation', models.FloatField(blank=True, null=True)),
                ('workload_units', models.FloatField(blank=True, null=True)),
                ('num_preparations', models.IntegerField(blank=True, null=True)),
                ('deloading', models.BooleanField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.facultymember')),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyRecord',
        ),
    ]
