# Generated by Django 5.2.1 on 2025-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_facultymember_facultyperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyperformance',
            name='year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='facultyperformance',
            name='semester',
            field=models.CharField(choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem')], max_length=25),
        ),
    ]
