# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_facultyperformance_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyperformance',
            old_name='year',
            new_name='school_year',
        ),
    ]
