# Generated by Django 5.2.1 on 2025-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_rename_year_facultyperformance_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_corr', models.FloatField(blank=True, null=True)),
                ('prep_corr', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
