# Generated by Django 5.2.1 on 2025-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_correlationresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANOVAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=100)),
                ('f_statistic', models.FloatField()),
                ('p_value', models.FloatField()),
                ('significant', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.CharField(max_length=100)),
                ('group2', models.CharField(max_length=100)),
                ('p_value', models.FloatField()),
                ('reject_null', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('average_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
